Update README.md
VikParuchuri/surya pull request #45
Opened 2024-03-02 11:48 UTC by tzktz

ModuleNotFoundError: No module named 'surya.model.segformer' 

Change This

From 
from surya.model.segformer import load_model, load_processor

To 
from surya.model.detection.segformer import load_model, load_processor

2024-07-25 02:20 UTC, DanielLima52 requested changes

2024-07-25 02:20 UTC, DanielLima52 commented on README.md
> +from surya.model.detection.segformer import load_model, load_processor
The true fix is: 

```suggestion
from surya.model.detection.model import load_model, load_processor
```

2024-07-29 01:08 UTC, iaminebriki commented
exactly as it was updated in this [commit](https://github.com/VikParuchuri/surya/commit/912ab76cf48e4bc9b5e90c55c53618b5f71d1ac3) for the "layout" and "text line detection" sections and forgotten for the first OCR section

very important!!

2024-10-31 11:00 UTC, iammosespaulr commented
The Docs have been updated!

2024-10-31 11:00 UTC, closed without merging